config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :essays do
    resources :research_cards
    resources :sections
    resources :sources
    member do
      get 'to_pdf'
      get 'to_md'
      get 'to_word'
    end
  end

  get '/essays/:essay_id/sections/:id/draft_edit', to: 'sections#edit_final', as: 'edit_final_essay_section'

  root "essays#index"
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :essay
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

    def index
      @essay = Essay.find(params[:essay_id])
      @sections = @essay.sections.order(order: :desc)
    end

    def show
      @essay = Essay.find(params[:essay_id])
      @section = @essay.sections.find(params[:id])
    end

    def new
      @essay = Essay.find(params[:essay_id])
      @section = @essay.sections.new
    end

    def create
      @essay = Essay.find(params[:essay_id])
      @section = @essay.sections.new(section_params)
      if @section.save
        redirect_to essay_section_path(@essay, @section)
      else
        render 'new'
      end
    end

    def edit
      @essay = Essay.find(params[:essay_id])
      @section = @essay.sections.find(params[:id])
    end

    def edit_final
      @essay = Essay.find(params[:essay_id])
      @section = @essay.sections.find(params[:id])
    end

    def update
      @essay = Essay.find(params[:essay_id])
      @section = @essay.sections.find(params[:id])
      if @section.update(section_params)
        redirect_to essay_section_path(@essay, @section)
      else
        render 'edit'
      end
    end

    def destroy
      @essay = Essay.find(params[:essay_id])
      @section = @essay.sections.find(params[:id])
      @section.destroy

      redirect_to essay_path(@essay)
    end

    private
      def section_params
        params.require(:section).permit(:title, :order, :outline, :rough_drafting, :final_draft)
      end
end

app/views/sections/_form.html.erb
<p><%= form_for ([@essay, @section]) do |f| %></p>

  <p><%= f.label :title %></p>
  <p><%= f.text_field :title %></p>

  <p><%= f.label "Position: " %></p>
  <p><%= f.number_field :order %></p>

  <p><%= f.label :outline %></p>
  <p><%= f.text_area :outline %></p>

  <p><%= f.label "Drafting Space:" %></p>
  <p><%= f.text_area :rough_drafting %></p>

  <p><%= f.label "Final or Working Draft:" %></p>
  <p><%= f.text_area :final_draft %></p>

  <%= f.submit :class => "btn waves-effect lime white-text"%>

<%end%>

app/views/sections/_section.html.erb
<li>
  <div class="collapsible-header">
    <i class="material-icons lime-text">layers</i><%= section.title %>
  </div>

  <div class="collapsible-body">
    <%= markdown(section.outline) %>
    <span class="secondary-content">
      <%= link_to essay_section_path(@essay, section), :class => "lime-text text-darken-1", :title => "MORE", :target => "_blank" do %>
        <i class="material-icons">flight_takeoff</i>
      <%end%>
      <%= link_to edit_essay_section_path(@essay, section), :class => "lime-text text-darken-1", :title => "EDIT", :target => "_blank" do %>
        <i class="material-icons">edit</i>
      <%end%>
      <%= link_to essay_section_path(@essay, section), method: :delete,
                             data: {confirm: "Are you sure you want to delete this section?"},
                             :class => "lime-text text-darken-1" do %>
        <i class="material-icons">delete</i>
      <%end%>
    </span>
  </div>
</li>

app/views/sections/edit.html.erb
<% @title = "Editing #{@section.title}" %>

<h1>Edit Section <%= @section.title %> </h1>

</br></br>

<%= render "form" %>

app/views/sections/edit_final.html.erb
<% @title = "Editing #{@section.title}" %>

<h2 class = "Fredericka" >Editing Current Draft for <%= @essay.title %> : <%= @section.title %> </h2>

<div class="sec_outline hoverable">
  <%= markdown(@section.outline) %>
</div>

<%= form_for ([@essay, @section]) do |f| %>
  <p><%= f.label "Draft: " %></p>
  <p><%= f.text_area :final_draft %></p>

  <%= f.submit "Save", :class => "btn waves-effect lime"%>

<%end%>

app/views/sections/index.html.erb
<% @title = @essay.title %>

<div class = "card hoverable paper">
  <h1><%= @essay.title %></h1>

  <% if @essay.sections.any? %>
    <% @essay.sections.order(:order).each do |section| %>
      <p><%= markdown(section.final_draft) unless section.final_draft.blank? %></p>
    <%end%>
  <%end%>

  <h5>Works Cited </h5>

  <%= render 'sources/works_cited' %>
</div>

app/views/sections/new.html.erb
<% @title = "New Section!" %>

<h1>Create new Section: </h1>

</br></br>

<%= render "form" %>

app/views/sections/show.html.erb
<% @title = @section.title %>

<h1 class="center"><%= @essay.title %></h1>
<h2 class="center" style="font-family: Fredericka the Great"><%= @section.title %></h2>

<div class="sec_outline hoverable">
  <p><%= markdown(@section.outline) unless @section.outline.blank? %></p>
</div>

<div class="sec_content">
  <h2>Drafting: </h2>
  <%= markdown(@section.rough_drafting) unless @section.rough_drafting.blank? %>
</div>

<div class="card hoverable sec_cleaned">
    <h2>Current Working Draft: </h2>
    <%= markdown(@section.final_draft) unless @section.final_draft.blank?%>
    </br></br>
    <%= link_to "EDIT", edit_final_essay_section_path(@essay, @section),
                        :class => 'btn-flat waves-effect lime-waves waves-lighten' %>
</div>

<div class="clearfix">
</div>

<%= link_to "EDIT", edit_essay_section_path(@essay, @section), :class => "btn lime"%>
<%= link_to "DELETE", essay_section_path(@essay, @section), method: :delete,
                       data: {confirm: "Are you sure you want to delete this section?"},
                       :class => "btn lime"%>