config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :essays do
    resources :research_cards
    resources :sections
    resources :sources
    member do
      get 'to_pdf'
      get 'to_md'
      get 'to_word'
    end
  end

  get '/essays/:essay_id/sections/:id/draft_edit', to: 'sections#edit_final', as: 'edit_final_essay_section'

  root "essays#index"
end

app/models/research_card.rb
class ResearchCard < ApplicationRecord
  belongs_to :essay
end

app/controllers/research_cards_controller.rb
class ResearchCardsController < ApplicationController

  def show
    @essay = Essay.find(params[:essay_id])
    @research_card = @essay.research_cards.find(params[:id])
  end

  def new
    @essay = Essay.find(params[:essay_id])
    @research_card = @essay.research_cards.new
  end

  def create
    @essay = Essay.find(params[:essay_id])
    @research_card = @essay.research_cards.new(research_card_params)
    if @research_card.save
      redirect_to essay_path(@essay)
    else
      render 'new'
    end
  end

  def edit
    @essay = Essay.find(params[:essay_id])
    @research_card = @essay.research_cards.find(params[:id])
  end

  def update
    @essay = Essay.find(params[:essay_id])
    @research_card = @essay.research_cards.find(params[:id])
    if @research_card.update(research_card_params)
      redirect_to essay_path(@essay)
    else
      render 'edit'
    end
  end

  def destroy
    @essay = Essay.find(params[:essay_id])
    @research_card = @essay.research_cards.find(params[:id])
    @research_card.destroy

    redirect_to essay_path(@essay)
  end

  private
    def research_card_params
      params.require(:research_card).permit(:title, :body)
    end
end

app/views/research_cards/_form.html.erb
<p><%= form_for ([@essay, @research_card]) do |f| %></p>

  <p><%= f.label :title %></p>
  <p><%= f.text_field :title %></p>

  <p><%= f.label :body %></p>
  <p><%= f.text_area :body %></p>

  <%= f.submit :class => "btn waves-effect blue lighten-2 white-text"%>

<%end%>

app/views/research_cards/_research_card.html.erb
<div class="col s12 m6">
  <div class="card hoverable sticky-action">
    <div class="card-image waves-effect waves-light">
      <%= image_tag("chalk.jpg", class:"activator") %>
    </div>
    <div class="card-content">
      <h3 class="card-title activator">
        <i class= "material-icons left blue-text lighten-2">grid_on</i>
          <% if research_card.title.blank? %>
            Research Card:
          <% else %>
            <%= truncate(research_card.title)%>
          <%end%>
        <i class="material-icons right">more_vert</i> </h3>
    </div>
    <div class="card-action">
      <%= link_to "edit", edit_essay_research_card_path(@essay, research_card),
                          :class => "blue-text lighten-3", :target => "_blank"%>
      <%= link_to "destroy", essay_research_card_path(@essay, research_card), method: :delete,
                             data: {confirm: "Are you sure you want to delete this research card?"},
                             :class => "blue-text lighten-3"%>
    </div>
    <div class="card-reveal">
      <h3 class="card-title activator">
        <% if research_card.title.blank? %>
          Research Card:
        <% else %>
          <%= research_card.title %>
        <%end%>
        <i class="material-icons right">close</i>
      </h3>
      <div class="body_rc">
        <%= markdown(research_card.body) %>
      </div>
    </br></br></br>
    </div>

  </div>
</div>

app/views/research_cards/_research_pod.html.erb
<div class="col s12 m6">
  <div class="card hoverable sticky-action">
    <div class="card-image waves-effect waves-light">
      <%= image_tag("chalk.jpg", class:"activator") %>
    </div>
    <div class="card-content">
      <h3 class="card-title activator">
        <i class= "material-icons left blue-text lighten-2">grid_on</i>
          <% if research_card.title.blank? %>
            Research Card:
          <% else %>
            <%= truncate(research_card.title)%>
          <%end%>
        <i class="material-icons right">more_vert</i> </h3>
    </div>
    <div class="card-action">
      <%= link_to "edit", edit_essay_research_card_path(@essay, research_card),
                          :class => "blue-text lighten-3", :target => "_blank"%>
      <%= link_to "destroy", essay_research_card_path(@essay, research_card), method: :delete,
                             data: {confirm: "Are you sure you want to delete this research card?"},
                             :class => "blue-text lighten-3"%>
    </div>
    <div class="card-reveal">
      <h3 class="card-title activator">
        <% if research_card.title.blank? %>
          Research Card:
        <% else %>
          <%= research_card.title %>
        <%end%>
        <i class="material-icons right">close</i>
      </h3>
      <%= markdown(research_card.body) %>
    </div>

  </div>
</div>

app/views/research_cards/edit.html.erb
<% @title = "Editing Research" %>

<h1>Edit <%= @research_card.title %></h1>

</br></br>

<%= render "form" %>

app/views/research_cards/new.html.erb
<% @title = "New Research Card!" %>


<h1>Create new Research Card!</h1>

</br></br>

<%= render "form" %>