config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :essays do
    resources :research_cards
    resources :sections
    resources :sources
    member do
      get 'to_pdf'
      get 'to_md'
      get 'to_word'
    end
  end

  get '/essays/:essay_id/sections/:id/draft_edit', to: 'sections#edit_final', as: 'edit_final_essay_section'

  root "essays#index"
end

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper purple lighten-3">
    <ul class="left">
      <!-- at some point, perhaps try to make this prettier?-->
      <li><%= link_to "Home", essays_path %></li>
      <% unless @essay.blank? || @title == "New Essay!" %>
        <li><%= link_to "Dashboard", essay_path(@essay) %></li>
      <% end %>
      <!-- on right of page? So it doesn't accidentally get clicked on. -->
      <li><%= link_to "New Essay!", new_essay_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<!-- TODO: fork + try to add PANDOC; perhaps build simple app first to see
how pandoc-ruby works?  -->
<html>
  <head>
    <title><%= @title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <div class="container">
      <%= yield %>
    </div>

    <%= render 'layouts/navbar' %>

</html>