config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :essays do
    resources :research_cards
    resources :sections
    resources :sources
    member do
      get 'to_pdf'
      get 'to_md'
      get 'to_word'
    end
  end

  get '/essays/:essay_id/sections/:id/draft_edit', to: 'sections#edit_final', as: 'edit_final_essay_section'

  root "essays#index"
end

app/models/essay.rb
class Essay < ApplicationRecord
  has_many :research_cards, :dependent => :destroy
  has_many :sections, :dependent => :destroy
  has_many :sources, :dependent => :destroy
end

app/controllers/essays_controller.rb
class EssaysController < ApplicationController

  def index
    @essays = Essay.all
  end

  def show
    @essay = Essay.find(params[:id])
  end

  def new
    @essay = Essay.new
  end

  def create
    @essay = Essay.new(essay_params)
    if @essay.save
      redirect_to essay_path(@essay)
    else
      render 'new'
    end
  end

  def edit
    @essay = Essay.find(params[:id])
  end

  def update
    @essay = Essay.find(params[:id])
    if @essay.update(essay_params)
      redirect_to essay_path(@essay)
    else
      render 'edit'
    end
  end

  def destroy
    @essay = Essay.find(params[:id])
    @essay.destroy

    redirect_to essays_path
  end

  # def to_tex
  #   @essay = Essay.find(params[:id])
  #   #NOTE: why does order need to be ascending here, descending rendering?
  #   @sections = @essay.sections.order(order: :asc)
  #   @tex = helpers.convert_latex(@sections)
  #   send_file(@tex, disposition: 'attatchment')
  #   #File.delete(@pdf) if File.exist?(@pdf)
  #   #redirect_to essay_path(@essay)
  # end

  #EXTERNAL facing function to be called by user
  def to_md
    _to_md(true)
  end

  #INTERNAL facing function for doing work of writing markdown; sending as download
  # if passed from external facing function
  def _to_md(download)
    @essay = Essay.find(params[:id])
    @sections = @essay.sections.order(order: :asc)
    @sources = Array.new
    @sources = @essay.sources.sort_by{|work| work.citation} unless @essay.sources.empty?
    @md = helpers.write_md(@sections, @sources)
    if download
      send_file(@md, type: 'md', disposition: 'attatchment')
    else
      @md
    end
  end

  def to_pdf
    @essay = Essay.find(params[:id])
    @md = _to_md(false)
    @output = "app/assets/files/test.pdf"
    command = "pandoc " + @md + " -o " + @output
    system(command)

    File.delete(@md) if File.exist?(@md)
    send_file @output, type: 'pdf', disposition: 'attatchment'

    #NOTE: will not download if you redirect. idk why?
    #NOTE: how to safely delete all generated files?
    #redirect_to essay_path(@essay)
  end

  def to_word
    @essay = Essay.find(params[:id])
    @md = _to_md(false)
    @output = "app/assets/files/draft.docx"
    command = "pandoc " + @md + " -o " + @output
    system(command)

    File.delete(@md) if File.exist?(@md)
    send_file @output, type: 'docx', disposition: 'attatchment'
  end

  private
    def essay_params
      params.require(:essay).permit(:title, :due_date, :prompt, :thesis)
    end
end

app/views/essays/_download_menu.html.erb
<!-- Hidden unless Prompt is clicked -->

<div class="download-content center">
  <h4>Download As:</h4>
  </br></br>
    <%= link_to "PDF", to_pdf_essay_path(@essay), :class => "waves-effect waves-light btn pink lighten-2"%>
    <%= link_to "Word Doc", to_word_essay_path(@essay), :class => "waves-effect waves-light btn pink lighten-2"%>
    <%= link_to "Markdown", to_md_essay_path(@essay), :class => "waves-effect waves-light btn pink lighten-2"%>
  </br></br>
</div> <!-- modal-content (hidden until above link is clicked)-->

app/views/essays/_fixed_action_menu.html.erb
<div class="fixed-action-btn">
  <a class="btn-floating btn-large purple lighten-3">
    <i class="large material-icons">assignment</i>
  </a>
  <ul>
    <li>
      <%= link_to edit_essay_path(@essay), :class => "btn-floating pink darken-2", :title => "Update Title, Due Date, Prompt, or Thesis" do %>
        <i class="material-icons">edit</i>
      <%end%>
    </li>
    <li>
      <%= link_to new_essay_research_card_path(@essay), :target => "_blank", :class => "btn-floating blue lighten-2", :title => "Add Research Card" do %>
        <i class="material-icons">grid_on</i>
      <%end%>
    </li>
    <li>
      <%= link_to new_essay_section_path(@essay), :target => "_blank", :class => "btn-floating lime", :title => "Add Section to Outline" do%>
        <i class="material-icons">layers</i>
      <%end%>
    </li>
    <li>
      <%= link_to new_essay_source_path(@essay), :target => "_blank", :class => "btn-floating orange lighten-2", :title => "Add Source" do%>
        <i class="material-icons">book</i>
      <%end%>
    </li>
    <li>
      <%= link_to essay_path(@essay), method: :delete, data: {confirm: "Are you sure you want to delete this essay?"}, :class => "btn-floating teal lighten-1", :title => "Delete Essay" do %>
        <i class="material-icons">delete_sweep</i>
      <%end%>
    </li>
    <li>
      <%= link_to "#download-modal", :class => "btn-floating pink lighten-2 modal-trigger", :title => "Download Essay" do%>
        <i class ="material-icons">file_download</i>
      <%end%>
    </li>
  </ul>
</div>

app/views/essays/_form.html.erb
<%= form_for @essay do |f| %>
  <p><%= f.label :title %></p>
  <p><%= f.text_field :title %></p>

  <p><%= f.label :due_date %></p>
  <p><%= f.date_field :due_date %></p>

  <p><%= f.label :prompt %></p>
  <p><%= f.text_area :prompt %></p>

  <p><%= f.label "Thesis or Driving Question:" %></p>
  <p><%= f.text_area :thesis %></p>

  <p><%= f.submit :class => "btn waves-effect purple lighten-3 white-text"%></p>

<%end%>

app/views/essays/edit.html.erb
<% @title="Edit #{@essay.title}" %>

<h1>Editing <%= @essay.title %></h1>

<%= render 'form' %>

app/views/essays/index.html.erb
<!-- Essay Index Carousel; Homepage -->

<!--TODO:-->
<!-- favicon -->
<!-- add tab capability to markdown parser -->
<!-- Backup, esp for local -->

<!-- Place to edit the Final Draft; not really sure about the functionality of this; want it to look
     continuous, but also want to have automatic update for sections? -->

<!-- Force new to make you pick a due date; right now crashes if not. -->

<!-- place that tells you how many days you have till it's due, how many weeks, etc? -->
<!-- System for logging time? -->
<!-- Independent of Essays, place to put general resources? EX: notes on MLA, structure of a French essay, etc etc;
Expandable Sidebar? -->
<!-- Figure out what's happening with the lack of bold text!!! I think it's not the markdown parser, though idk so check.-->


<% @title="Essay Dashboard" %>

<div id="index-wrapper" class="wrapper">

  <h1 class="center">Your Essay Dashboards:</h1>

  <%if @essays.any?%>

    <div id="index-carousel" class="carousel">

      <%@essays.order('created_at DESC').each do |essay|%>

        <div class="card carousel-item index-card">

          <div class="card-image waves-effect waves-light">
            <%= image_tag("chalk.jpg", :class => "activator") %>
          </div> <!-- Card image -->

          <div class="card-content">
            <h3 class="card-title activator"> <%= essay.title %>
              <i class="material-icons right">more_vert</i>
            </h3>
          </div> <!-- Card Content -->


          <div class="card-action">

          </div>

          <div class="card-reveal">

            <h3 class="card-title activator"> <%= essay.title %>
              <i class="material-icons right">close</i>
            </h3>

            <p class="text-purple lighten-3">Due: <%= essay.due_date %></p>

            <%unless essay.prompt.blank? %>
              <h5>Prompt:</h5>
              <p><%= markdown(essay.prompt) %></p>
              </br></br>
            <%end%>

            <%unless essay.thesis.blank? %>
              <h5>Thesis / Driving Question:</h5>
              <p><%= markdown(essay.thesis) %></p>
            <%end%>

            <%= link_to "More", essay_path(essay),
                :class => "btn waves-effect purple lighten-3 bottom" %>

            <%= link_to "Delete", essay_path(essay), method: :delete,
                data: {confirm: "Are you sure you want to delete this essay?"},
                :class => "btn waves-effect purple lighten-3 bottom" %>
            </br></br></br>
          </div> <!-- Card Reveal -->

        </div> <!-- Essay Card -->

      <%end%> <!-- Essays.each do -->

    </div> <!--Index Carousel -->
  <% else %>
    <h3>To get started on your first essay, click <i>New Essay</i> below! Good luck writing!</h3>
  <%end%> <!-- if else Essays.any? -->

  <div class="clearfix"></div>

</div> <!--Index Wrapper -->

<script>
    $('.carousel').carousel();
</script>

app/views/essays/new.html.erb
<% @title = "New Essay!" %>

<h1>Create an Essay!</h1>

<%= render 'form' %>

app/views/essays/show.html.erb
<% @title= @essay.title %>

<h1 class="center"><%= @essay.title %></h1>
<p class="center">Due: <%= @essay.due_date.strftime("%B %d, %Y") %></p>

<div class="center-align">
  <%= link_to "View", essay_sections_path(@essay), :class => "waves-effect waves-purple btn-flat modal-trigger center-align" %>
  <a class="waves-effect waves-purple btn-flat modal-trigger" href="#prompt-modal">Prompt</a>
</div>

<% unless @essay.prompt.blank? %>
  <!-- Hidden unless Prompt is clicked -->
  <div id="prompt-modal" class="modal">
    <div class="modal-content">
      <h4>Prompt</h4>
      <p><%= markdown(@essay.prompt) %></p>
    </div> <!-- modal-content (hidden until above link is clicked)-->
    <div class="modal-footer">
      <%= link_to "Edit", edit_essay_path(@essay), :class => "waves-effect waves-light btn purple lighten-3"%>
      <a class="waves-effect waves-light btn purple lighten-3 modal-trigger" href="">Close</a>
    </div> <!-- modal-footer -->
  </div> <!-- prompt-modal -->
<%end%>

<!-- Hidden unless download is clicked (in fixed action)-->
<div id="download-modal" class="modal">
  <%= render "download_menu" %>
</div>



<% unless @essay.thesis.blank? %>
  <div class = "card horizontal">
    <div class ="card-content">
      <span class = "card-title">Thesis or Driving Question:</span>
      <%= markdown(@essay.thesis) %>
    </div> <!-- card-content -->
  </div> <!-- card-title -->
<%end%>

<!--NOTE: for ordering oldest first!!!!-->
<% if @essay.research_cards.any? %>
  <div class="row">
    <%= render @essay.research_cards.order(id: :asc) %>
  </div>
<% end %>

<% if @essay.sections.any? %>
  <div class="section-outline">
    <ul class="collapsible" data-collapsible="expandable">
      <li>
        <div class="collapsible-header">
          <h4>Working Outline</h4>
        </div> <!-- collapsible-header -->
      </li>
      <%= render @essay.sections.order(:order) %>
    </ul>
  </div> <!-- section-outline -->
<% end %>

<% if @essay.sources.any? %>
  <div class="collection with-header">
    <h5 class="collection-header">
      <%= link_to "Works Cited and Readings", essay_sources_path(@essay), :class => "black-text" %>
    </h5>
    <%= render @essay.sources %>
  </div>
<%end%>

<%= render "fixed_action_menu" %>

<script>
  $('.modal').modal();
  $('.fixed-action-btn').floatingActionButton();
  $('.collapsible').collapsible();
</script>